//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollegeDetail
    {
        public int Id { get; set; }
        public string College_Name { get; set; }
        public string Unversity_Name { get; set; }
        public string state { get; set; }
        public string City { get; set; }
        public string Branch { get; set; }
        public Nullable<double> Open { get; set; }
        public Nullable<double> OBC { get; set; }
        public Nullable<double> SC { get; set; }
        public Nullable<double> ST { get; set; }
        public Nullable<double> EWS { get; set; }
        public int Seat_Avability { get; set; }
        public string Facility { get; set; }
    }
}
